# Generated by Django 5.0.6 on 2024-05-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fan_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Dust Types',
                'ordering': ('name',),
            },
        ),
    ]
