# Generated by Django 5.0.6 on 2024-05-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fan_market', '0002_dust'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='dust',
            field=models.ManyToManyField(to='Fan_market.dust'),
        ),
    ]
