# Generated by Django 5.0.6 on 2024-05-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fan_market', '0003_mainitem_dust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainitem',
            name='max_cleaning_efficiency',
        ),
    ]
