# Generated by Django 5.0.6 on 2024-05-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fan_market', '0004_remove_mainitem_max_cleaning_efficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainitem',
            old_name='min_cleaning_efficiency',
            new_name='cleaning_efficiency',
        ),
    ]
