# Generated by Django 5.0.6 on 2024-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fan_market', '0005_rename_min_cleaning_efficiency_mainitem_cleaning_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='cleaning_efficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
