# Generated by Django 5.0.6 on 2024-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fan_market', '0006_alter_mainitem_cleaning_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='concentration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
